baseURL: https://www.st-0q.com
canonifyurls: true
languageCode: ja
title: 個人ブログ
theme: mini
paginate: 5
googleAnalytics: G-EY2ZS7XBFR

hasCJKLanguage: true
permalinks:
  posts: /posts/:slug/

markup:
  highlight:
    guessSyntax: true
    style: dracula
    tabWidth: 2
  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: false
  goldmark:
    renderer:
      unsafe: true

social:
  github: https://github.com/st0q

params:
  author: st0q
  bio: Web Engineer
  description: My Blog
  enableRSS: true
  enableComments: false
  enableGoogleAnalytics: true
  enableEmoji: true
  showToc: true
